version: "3.8"

services:
  # Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.97.0
    container_name: otel-collector
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8888:8888"   # OTEL 자체 metrics
      - "8889:8889"   # Prometheus
    volumes:
      - /:/hostfs:ro  # hostmetrics
      - ./monitoring/otel-config.yml:/etc/otel/config.yaml
    command: ["--config=/etc/otel/config.yaml"]
    depends_on:
      - elasticsearch

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"

  # Metrics
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--log.level=debug"
    restart: unless-stopped

  # Traces
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.21
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  jaeger-query:
    image: jaegertracing/jaeger-query:1.57
    container_name: jaeger-query
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES-SERVER-URLS=https://elasticsearch:9200
    ports:
      - "16686:16686"
    depends_on:
      - elasticsearch

  # Visualization
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped

volumes:
  grafana-storage:
  es-data: