receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  logging:
    verbosity: detailed

processors:
  batch:
    send_batch_size: 100
    timeout: 10s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
  telemetry:
    metrics:
      address: 0.0.0.0:8888
      level: detailed
