spring:
  application:
    name: momo

  profiles:
    active: auth

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true                    # Flyway 활성화
    locations: classpath:db/migration
    baseline-on-migrate: true        # 기존 DB 있어도 마이그레이션 적용 가능
    clean-disabled: false            # clean 기능 활성화 (개발용)

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  messages:
    basename: validations
    encoding: UTF-8

toss:
  payments:
    secret-key: ${TOSS_SECRET_KEY}
    client-key: ${TOSS_CLIENT_KEY}
    base-url: ${TOSS_BASE_URL}
