name: Deploy with ECR
on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: momo # ECR 리포지토리 이름
  CONTAINER_NAME: momo



jobs:
  deploy-job:
    runs-on: ubuntu-latest # 우분투 환경

    steps:
      - name: Checkout repository # 리포지토리 코드 runner 에 clone
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew clean build -x test # 테스트 제외 빌

      - name: Configure AWS Credentials # AWS 인증 정보 설정
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR # 내부적으로 aws ecr get-login-password 을 실행해서 받은 토큰으로 이후 명령을 수행
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          # 도커 이미지 빌드
          docker build --platform linux/amd64 -t momo:latest .
          
          # 로컬 momo:latest 이미지를 ECR용 레포지토리 경로로 태깅
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ secrets.AWS_ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          
          # ECR에 푸시
          docker push ${{ secrets.AWS_ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}       # EC2 퍼블릭 IP 또는 DNS
          username: ${{ secrets.EC2_USER }}       # ec2-user, ubuntu 등
          key: ${{ secrets.EC2_SSH_KEY }}    # SSH private key (GitHub Secret)
          script: |
            
            # EC2에서 AWS 권한 사용을 위해 환경변수로 자격증명 설정
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_REGION=${{ secrets.AWS_REGION }}
            
            # AWS CLI 설치
            sudo apt-get update
            sudo apt-get install -y unzip
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            
            # Docker 설치 및 서비스 시작
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl enable docker
            sudo systemctl start docker
            
            # ECR에 로그인
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
            | sudo docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY }}
            
            # 컨테이너 중지 및 삭제
            sudo docker stop ${{ env.CONTAINER_NAME }} || true
            sudo docker rm   ${{ env.CONTAINER_NAME }} || true
            
            # 도커 이미지 Pull & Run
            sudo docker pull ${{ secrets.AWS_ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            sudo docker run -d --restart unless-stopped \
              --name ${{ env.CONTAINER_NAME }} \
              -p 8080:8080 \
              -e DB_URL='${{ secrets.DB_URL }}' \
              -e DB_USERNAME='${{ secrets.DB_USERNAME }}' \
              -e DB_PASSWORD='${{ secrets.DB_PASSWORD }}' \
              -e SECRET_KEY='${{ secrets.SECRET_KEY }}' \
              -e NAVER_CLIENT_ID='${{ secrets.NAVER_CLIENT_ID }}' \
              -e NAVER_CLIENT_SECRET='${{ secrets.NAVER_CLIENT_SECRET }}' \
              -e GOOGLE_CLIENT_ID='${{ secrets.GOOGLE_CLIENT_ID }}' \
              -e GOOGLE_CLIENT_SECRET='${{ secrets.GOOGLE_CLIENT_SECRET }}' \
              -e TOSS_SECRET_KEY='${{ secrets.TOSS_SECRET_KEY }}' \
              -e TOSS_CLIENT_KEY='${{ secrets.TOSS_CLIENT_KEY }}' \
              -e TOSS_BASE_URL='${{ secrets.TOSS_BASE_URL }}' \
              -e WEBCLIENT_SECRET_KEY='${{ secrets.WEBCLIENT_SECRET_KEY }}' \
             ${{ secrets.AWS_ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            
            
